# Generated by Django 4.2.2 on 2023-06-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='mobile_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
